### ISSUE TITLE
is it supposed to to that ? missing params/labels etc

### ISSUE THREAD

**Issue by higgledyhiggles** [sdao/iWaveOcean#4]
- plugin appears under create/standard (not `standard primitives`) button/icon has no text label, blank
- modifier window is blank, no parameters at all
- it animates like waves ok just can`t edit it.

**Comment by higgledyhiggles** [comment]
ignore me.. modifier window is fine.

**Comment by sdao** [comment]
Thanks for the report anyways :)
If you're having any other issues, keep filing issues or you can email me at <stevedao@gmail.com>.
Thanks!
